// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFQjB8m1oI-GEXGOrLV3o3gf2OkeY-UUM',
    appId: '1:128896874127:web:ae95c9bea90043102262fa',
    messagingSenderId: '128896874127',
    projectId: 'chat-app-a6548',
    authDomain: 'chat-app-a6548.firebaseapp.com',
    storageBucket: 'chat-app-a6548.firebasestorage.app',
    measurementId: 'G-ZKCXG1F6ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA26CkWplYO3iHVvMR5t8KnzIa01Ct83U',
    appId: '1:128896874127:android:46c87932e32114892262fa',
    messagingSenderId: '128896874127',
    projectId: 'chat-app-a6548',
    storageBucket: 'chat-app-a6548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC01PpdlKCvs_B2O9g0msqJ3F12rVGN8ws',
    appId: '1:128896874127:ios:77271366f5f769052262fa',
    messagingSenderId: '128896874127',
    projectId: 'chat-app-a6548',
    storageBucket: 'chat-app-a6548.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC01PpdlKCvs_B2O9g0msqJ3F12rVGN8ws',
    appId: '1:128896874127:ios:77271366f5f769052262fa',
    messagingSenderId: '128896874127',
    projectId: 'chat-app-a6548',
    storageBucket: 'chat-app-a6548.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFQjB8m1oI-GEXGOrLV3o3gf2OkeY-UUM',
    appId: '1:128896874127:web:4c33f8ffefbaa5a82262fa',
    messagingSenderId: '128896874127',
    projectId: 'chat-app-a6548',
    authDomain: 'chat-app-a6548.firebaseapp.com',
    storageBucket: 'chat-app-a6548.firebasestorage.app',
    measurementId: 'G-5TVP0GVDTH',
  );
}
